"""
Sample Data

Auto-generated from rulebook
Model: FractalsAndPowerLaws_CMCC
Generated: 2025-12-11 21:02:00 UTC

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: python rulebook-to-python.py
"""
from typing import Dict, List
from .models import System, Scale, SystemStats


def load_sample_data() -> Dict[str, List]:
    """Load sample data from rulebook"""
    data = {}

    # Each row is a fractal or power-law system described in a common schema.
    data['systems'] = [
        System(system_id="Sierpinski", display_name="Sierpinski Triangle", class="fractal", base_scale=1.0, scale_factor=0.5, measure_name="black_triangle_count", fractal_dimension=1.585, theoretical_log_log_slope=-1.585),
        System(system_id="Koch", display_name="Koch Snowflake (edge)", class="fractal", base_scale=1.0, scale_factor=0.3333333333, measure_name="edge_length_total", fractal_dimension=1.262, theoretical_log_log_slope=-0.262),
        System(system_id="ZipfWords", display_name="Zipf word frequencies", class="power_law", base_scale=1.0, scale_factor=2.0, measure_name="relative_frequency", fractal_dimension=None, theoretical_log_log_slope=-1.0),
        System(system_id="ScaleFreeNet", display_name="Scale-free network degrees", class="power_law", base_scale=1.0, scale_factor=2.0, measure_name="node_count_at_degree", fractal_dimension=None, theoretical_log_log_slope=-2.5),
    ]

    # Generic log–log points for each system at multiple iterations / scales.
    data['scales'] = [
        Scale(scale_id="Sierpinski_0", system="Sierpinski", iteration=0, measure=1.0),
        Scale(scale_id="Sierpinski_1", system="Sierpinski", iteration=1, measure=3.0),
        Scale(scale_id="Sierpinski_2", system="Sierpinski", iteration=2, measure=9.0),
        Scale(scale_id="Sierpinski_3", system="Sierpinski", iteration=3, measure=27.0),
        Scale(scale_id="Koch_0", system="Koch", iteration=0, measure=1.0),
        Scale(scale_id="Koch_1", system="Koch", iteration=1, measure=1.3333333333),
        Scale(scale_id="Koch_2", system="Koch", iteration=2, measure=1.7777777777),
        Scale(scale_id="Koch_3", system="Koch", iteration=3, measure=2.3703703703),
        Scale(scale_id="ZipfWords_0", system="ZipfWords", iteration=0, measure=1.0),
        Scale(scale_id="ZipfWords_1", system="ZipfWords", iteration=1, measure=0.5),
        Scale(scale_id="ZipfWords_2", system="ZipfWords", iteration=2, measure=0.25),
        Scale(scale_id="ZipfWords_3", system="ZipfWords", iteration=3, measure=0.125),
        Scale(scale_id="ScaleFreeNet_0", system="ScaleFreeNet", iteration=0, measure=1.0),
        Scale(scale_id="ScaleFreeNet_1", system="ScaleFreeNet", iteration=1, measure=0.1767766953),
        Scale(scale_id="ScaleFreeNet_2", system="ScaleFreeNet", iteration=2, measure=0.03125),
        Scale(scale_id="ScaleFreeNet_3", system="ScaleFreeNet", iteration=3, measure=0.0055242717),
    ]

    # Statistical analysis of each system's log-log behavior, with rollups from scales and lookups to systems.
    data['system_stats'] = [
        SystemStats(system_stats_id="Sierpinski_Stats", system="Sierpinski", analysis_name="Sierpinski Triangle Analysis", status="validated"),
        SystemStats(system_stats_id="Koch_Stats", system="Koch", analysis_name="Koch Snowflake Analysis", status="validated"),
        SystemStats(system_stats_id="ZipfWords_Stats", system="ZipfWords", analysis_name="Zipf Word Frequency Analysis", status="validated"),
        SystemStats(system_stats_id="ScaleFreeNet_Stats", system="ScaleFreeNet", analysis_name="Scale-Free Network Analysis", status="validated"),
    ]

    return data