"""
Utility Functions

Auto-generated from rulebook
Model: FractalsAndPowerLaws_CMCC
Generated: 2025-12-11 21:36:10 UTC

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: python rulebook-to-python.py
"""
from typing import Dict, List
from .models import System, Scale, SystemStats


def build_systems_dict(systems: List[System]) -> Dict[str, System]:
    """Build a dictionary of systems keyed by system_id"""
    return {s.system_id: s for s in systems}


def calculate_all_scales(scales: List[Scale], systems_dict: Dict[str, System]):
    """Calculate all derived fields for all scales"""
    for item in scales:
        # Calculate in dependency order
        item.calculate_base_scale(systems_dict)
        item.calculate_scale_factor(systems_dict)
        item.calculate_scale_factor_power()
        item.calculate_scale()
        item.calculate_log_scale()
        item.calculate_log_measure()

def calculate_all_system_stats(system_stats: List[SystemStats], systems_dict: Dict[str, System], scales: List[Scale]):
    """Calculate all derived fields for all system_stats"""
    for item in system_stats:
        # Calculate in dependency order
        item.calculate_system_display_name(systems_dict)
        item.calculate_theoretical_log_log_slope(systems_dict)
        item.calculate_point_count(scales)
        item.calculate_min_log_scale(scales)
        item.calculate_max_log_scale(scales)
        item.calculate_min_log_measure(scales)
        item.calculate_max_log_measure(scales)
        item.calculate_delta_log_measure()
        item.calculate_delta_log_scale()
        item.calculate_empirical_log_log_slope()
        item.calculate_slope_error()


def validate_system(stats: SystemStats, tolerance: float = 0.001) -> bool:
    """Check if empirical slope matches theoretical slope within tolerance"""
    return abs(stats._slope_error or 0) < tolerance
