"""
Utility Functions

Auto-generated from rulebook
Model: FractalsAndPowerLaws_CMCC
Generated: 2025-12-11 21:02:00 UTC

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: python rulebook-to-python.py
"""
from typing import Dict, List
from .models import System, Scale, SystemStats


def build_systems_dict(systems: List[System]) -> Dict[str, System]:
    """Build a dictionary of systems keyed by system_id"""
    return {s.system_id: s for s in systems}


def calculate_all_scales(scales: List[Scale], systems_dict: Dict[str, System]):
    """Calculate all derived fields for all scales"""
    for scale in scales:
        # Calculate in dependency order
        scale.calculate_base_scale(systems_dict)
        scale.calculate_scale_factor(systems_dict)
        scale.calculate_scale_factor_power()
        scale.calculate_scale(systems_dict)
        scale.calculate_log_scale(systems_dict)
        scale.calculate_log_measure()


def calculate_all_stats(stats_list: List[SystemStats], systems_dict: Dict[str, System], scales: List[Scale]):
    """Calculate all derived fields for all system stats"""
    for stats in stats_list:
        # Calculate in dependency order
        stats.calculate_system_display_name(systems_dict)
        stats.calculate_theoretical_log_log_slope(systems_dict)
        stats.calculate_point_count(scales)
        stats.calculate_min_log_scale(scales)
        stats.calculate_max_log_scale(scales)
        stats.calculate_min_log_measure(scales)
        stats.calculate_max_log_measure(scales)
        stats.calculate_delta_log_measure()
        stats.calculate_delta_log_scale()
        stats.calculate_empirical_log_log_slope()
        stats.calculate_slope_error()


def validate_system(stats: SystemStats, tolerance: float = 0.001) -> bool:
    """Check if empirical slope matches theoretical slope within tolerance"""
    return abs(stats._slope_error or 0) < tolerance
