//
// Sample Data
//
// Auto-generated from rulebook
// Model: FractalsAndPowerLaws_CMCC
// Generated: 2025-12-11 21:37:34 UTC
//
// DO NOT EDIT THIS FILE MANUALLY
// Regenerate by running: python rulebook-to-golang.py
//
package rulebook


// LoadSampleData loads sample data from rulebook
func LoadSampleData() map[string]interface{} {
    data := make(map[string]interface{})

    // Each row is a fractal or power-law system described in a common schema.
    data["systems"] = []*System{
        &System{Systemid: "Sierpinski", Displayname: "Sierpinski Triangle", Class: "fractal", Basescale: 1.0, Scalefactor: 0.5, Measurename: "black_triangle_count", Fractaldimension: 1.585, Theoreticalloglogslope: -1.585},
        &System{Systemid: "Koch", Displayname: "Koch Snowflake (edge)", Class: "fractal", Basescale: 1.0, Scalefactor: 0.3333333333, Measurename: "edge_length_total", Fractaldimension: 1.262, Theoreticalloglogslope: -0.262},
        &System{Systemid: "ZipfWords", Displayname: "Zipf word frequencies", Class: "power_law", Basescale: 1.0, Scalefactor: 2.0, Measurename: "relative_frequency", Theoreticalloglogslope: -1.0},
        &System{Systemid: "ScaleFreeNet", Displayname: "Scale-free network degrees", Class: "power_law", Basescale: 1.0, Scalefactor: 2.0, Measurename: "node_count_at_degree", Theoreticalloglogslope: -2.5},
        &System{Systemid: "Sandpile", Displayname: "Sandpile avalanches", Class: "power_law", Basescale: 1.0, Scalefactor: 2.0, Measurename: "relative_frequency_of_avalanches", Theoreticalloglogslope: -1.0},
        &System{Systemid: "Earthquakes", Displayname: "Earthquake energies", Class: "power_law", Basescale: 1.0, Scalefactor: 2.0, Measurename: "relative_frequency_of_quakes", Theoreticalloglogslope: -1.0},
        &System{Systemid: "ForestFires", Displayname: "Forest fire sizes", Class: "power_law", Basescale: 1.0, Scalefactor: 2.0, Measurename: "relative_frequency_of_fires", Theoreticalloglogslope: -1.3},
    },

    // Generic log–log points for each system at multiple iterations / scales.
    data["scales"] = []*Scale{
        &Scale{Scaleid: "Sierpinski_0", System: "Sierpinski", Iteration: 0, Measure: 1.0},
        &Scale{Scaleid: "Sierpinski_1", System: "Sierpinski", Iteration: 1, Measure: 3.0},
        &Scale{Scaleid: "Sierpinski_2", System: "Sierpinski", Iteration: 2, Measure: 9.0},
        &Scale{Scaleid: "Sierpinski_3", System: "Sierpinski", Iteration: 3, Measure: 27.0},
        &Scale{Scaleid: "Koch_0", System: "Koch", Iteration: 0, Measure: 1.0},
        &Scale{Scaleid: "Koch_1", System: "Koch", Iteration: 1, Measure: 1.3333333333},
        &Scale{Scaleid: "Koch_2", System: "Koch", Iteration: 2, Measure: 1.7777777777},
        &Scale{Scaleid: "Koch_3", System: "Koch", Iteration: 3, Measure: 2.3703703703},
        &Scale{Scaleid: "ZipfWords_0", System: "ZipfWords", Iteration: 0, Measure: 1.0},
        &Scale{Scaleid: "ZipfWords_1", System: "ZipfWords", Iteration: 1, Measure: 0.5},
        &Scale{Scaleid: "ZipfWords_2", System: "ZipfWords", Iteration: 2, Measure: 0.25},
        &Scale{Scaleid: "ZipfWords_3", System: "ZipfWords", Iteration: 3, Measure: 0.125},
        &Scale{Scaleid: "ScaleFreeNet_0", System: "ScaleFreeNet", Iteration: 0, Measure: 1.0},
        &Scale{Scaleid: "ScaleFreeNet_1", System: "ScaleFreeNet", Iteration: 1, Measure: 0.1767766953},
        &Scale{Scaleid: "ScaleFreeNet_2", System: "ScaleFreeNet", Iteration: 2, Measure: 0.03125},
        &Scale{Scaleid: "ScaleFreeNet_3", System: "ScaleFreeNet", Iteration: 3, Measure: 0.0055242717},
        &Scale{Scaleid: "Sandpile_0", System: "Sandpile", Iteration: 0, Measure: 1.0},
        &Scale{Scaleid: "Sandpile_1", System: "Sandpile", Iteration: 1, Measure: 0.5},
        &Scale{Scaleid: "Sandpile_2", System: "Sandpile", Iteration: 2, Measure: 0.25},
        &Scale{Scaleid: "Sandpile_3", System: "Sandpile", Iteration: 3, Measure: 0.125},
        &Scale{Scaleid: "Earthquakes_0", System: "Earthquakes", Iteration: 0, Measure: 1.0},
        &Scale{Scaleid: "Earthquakes_1", System: "Earthquakes", Iteration: 1, Measure: 0.5},
        &Scale{Scaleid: "Earthquakes_2", System: "Earthquakes", Iteration: 2, Measure: 0.25},
        &Scale{Scaleid: "Earthquakes_3", System: "Earthquakes", Iteration: 3, Measure: 0.125},
        &Scale{Scaleid: "ForestFires_0", System: "ForestFires", Iteration: 0, Measure: 1.0},
        &Scale{Scaleid: "ForestFires_1", System: "ForestFires", Iteration: 1, Measure: 0.406138466},
        &Scale{Scaleid: "ForestFires_2", System: "ForestFires", Iteration: 2, Measure: 0.1649530609},
        &Scale{Scaleid: "ForestFires_3", System: "ForestFires", Iteration: 3, Measure: 0.067020118},
    },

    // Statistical analysis of each system's log-log behavior, with rollups from scales and lookups to systems.
    data["system_stats"] = []*SystemStats{
        &SystemStats{Systemstatsid: "Sierpinski_Stats", System: "Sierpinski", Analysisname: "Sierpinski Triangle Analysis", Status: "validated"},
        &SystemStats{Systemstatsid: "Koch_Stats", System: "Koch", Analysisname: "Koch Snowflake Analysis", Status: "validated"},
        &SystemStats{Systemstatsid: "ZipfWords_Stats", System: "ZipfWords", Analysisname: "Zipf Word Frequency Analysis", Status: "validated"},
        &SystemStats{Systemstatsid: "ScaleFreeNet_Stats", System: "ScaleFreeNet", Analysisname: "Scale-Free Network Analysis", Status: "validated"},
        &SystemStats{Systemstatsid: "Sandpile_Stats", System: "Sandpile", Analysisname: "Sandpile Avalanche Analysis", Status: "validated"},
        &SystemStats{Systemstatsid: "Earthquakes_Stats", System: "Earthquakes", Analysisname: "Earthquake Energy Analysis", Status: "validated"},
        &SystemStats{Systemstatsid: "ForestFires_Stats", System: "ForestFires", Analysisname: "Forest Fire Size Analysis", Status: "validated"},
    },

    return data
}