-- ============================================================================
-- DROP AND CREATE TABLES - Clean slate + Normalized schema
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Tables: 3
-- Total Raw Fields: 13
-- ============================================================================

-- ============================================================================
-- DROP ALL OBJECTS - Clean slate for database
-- ============================================================================

DO $$ 
DECLARE r RECORD; v_count INTEGER := 0;
BEGIN
    RAISE NOTICE 'Dropping views...';
    FOR r IN (SELECT table_name FROM information_schema.views WHERE table_schema = 'public') LOOP
        EXECUTE 'DROP VIEW IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % views', v_count; v_count := 0;
    
    RAISE NOTICE 'Dropping functions...';
    FOR r IN (SELECT DISTINCT p.proname as function_name, pg_get_function_identity_arguments(p.oid) as function_args
              FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid
              WHERE n.nspname = 'public' AND p.prokind = 'f') LOOP
        EXECUTE 'DROP FUNCTION IF EXISTS ' || quote_ident(r.function_name) || '(' || r.function_args || ') CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % functions', v_count; v_count := 0;
    
    RAISE NOTICE 'Dropping tables...';
    FOR r IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE') LOOP
        EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % tables', v_count;
END $$;

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- systems: Each row is a fractal or power-law system described in a common schema.
CREATE TABLE systems (
  system_id                           TEXT                 PRIMARY KEY,
  display_name                        TEXT                ,
  class                               TEXT                ,
  base_scale                          NUMERIC             ,
  scale_factor                        NUMERIC             ,
  measure_name                        TEXT                ,
  fractal_dimension                   NUMERIC             ,
  theoretical_log_log_slope           NUMERIC             
);

-- scales: Generic log–log points for each system at multiple iterations / scales.
CREATE TABLE scales (
  scale_id                            TEXT                 PRIMARY KEY,
  system_id                           TEXT                 NOT NULL,
  iteration                           INTEGER              NOT NULL,
  measure                             NUMERIC             
);

-- system_stats: Aggregated log–log slope estimates per system, keeping slope separate from fractal dimension.
CREATE TABLE system_stats (
  system_id                           TEXT                 PRIMARY KEY
);

