-- ============================================================================
-- DROP AND CREATE TABLES - Clean slate + Normalized schema
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Tables: 6
-- Total Raw Fields: 37
-- ============================================================================

-- ============================================================================
-- DROP ALL OBJECTS - Clean slate for database
-- ============================================================================

DO $$ 
DECLARE r RECORD; v_count INTEGER := 0;
BEGIN
    RAISE NOTICE 'Dropping views...';
    FOR r IN (SELECT table_name FROM information_schema.views WHERE table_schema = 'public') LOOP
        EXECUTE 'DROP VIEW IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % views', v_count; v_count := 0;
    
    RAISE NOTICE 'Dropping functions...';
    FOR r IN (SELECT DISTINCT p.proname as function_name, pg_get_function_identity_arguments(p.oid) as function_args
              FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid
              WHERE n.nspname = 'public' AND p.prokind = 'f') LOOP
        EXECUTE 'DROP FUNCTION IF EXISTS ' || quote_ident(r.function_name) || '(' || r.function_args || ') CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % functions', v_count; v_count := 0;
    
    RAISE NOTICE 'Dropping tables...';
    FOR r IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE') LOOP
        EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % tables', v_count;
END $$;

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- systems: Each row is a fractal or power-law system described in a common schema.
CREATE TABLE systems (
  system_id                           TEXT                 PRIMARY KEY,
  display_name                        TEXT                ,
  class                               TEXT                ,
  base_scale                          INTEGER             ,
  scale_factor                        NUMERIC             ,
  measure_name                        TEXT                ,
  fractal_dimension                   NUMERIC             ,
  theoretical_log_log_slope           NUMERIC             
);

-- scales: Generic log–log points for each system at multiple iterations / scales.
CREATE TABLE scales (
  scale_id                            TEXT                 PRIMARY KEY,
  "system"                            TEXT                ,
  iteration                           INTEGER             ,
  measure                             NUMERIC             ,
  is_projected                        BOOLEAN             ,
  data_regime                         TEXT                ,
  measurement_model                   TEXT                
);

-- system_stats: Statistical analysis of each system's log-log behavior, with rollups from scales and lookups to systems.
CREATE TABLE system_stats (
  system_stats_id                     TEXT                 PRIMARY KEY,
  "system"                            TEXT                ,
  analysis_name                       TEXT                ,
  status                              TEXT                
);

-- measurement_models: Measurement/de-idealization specs used to produce or interpret real-world (noisy, finite-size, discretized) scale records.
CREATE TABLE measurement_models (
  measurement_model_id                TEXT                 PRIMARY KEY,
  "system"                            TEXT                ,
  data_regime                         TEXT                ,
  noise_type                          TEXT                ,
  noise_sigma                         NUMERIC             ,
  cutoff_min_scale                    NUMERIC             ,
  cutoff_max_scale                    NUMERIC             ,
  discretization_type                 TEXT                ,
  discretization_param                TEXT                
);

-- observed_scales: Noisy, finite-range, discretized observations of each system's scaling law. Mirrors scales but with DataRegime='measured'.
CREATE TABLE observed_scales (
  observed_scale_id                   TEXT                 PRIMARY KEY,
  "system"                            TEXT                ,
  measurement_model                   TEXT                ,
  iteration                           INTEGER             ,
  measure                             NUMERIC             ,
  data_regime                         TEXT                
);

-- inference_runs: Inference outputs (fits and residual geometry) computed from observed_scales relative to each system fixed point.
CREATE TABLE inference_runs (
  inference_run_id                    TEXT                 PRIMARY KEY,
  "system"                            TEXT                ,
  data_regime                         TEXT                ,
  measurement_model                   TEXT                ,
  fit_method                          TEXT                ,
  fitted_slope                        NUMERIC             ,
  fitted_intercept                    NUMERIC             ,
  r2                                  NUMERIC             ,
  residual_rms                        NUMERIC             ,
  residual_max_abs                    NUMERIC             ,
  orthogonal_rms                      NUMERIC             
);

