-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- ============================================================================

-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- calc_scales_scale
-- Field: scales.Scale
-- Type: calculated | DataType: number | Returns: NUMERIC
-- Formula: ={{BaseScale}}*({{ScaleFactor}}^{{Iteration}})
-- ============================================================================
-- CRITICAL FUNCTION VALIDATION CODE - DO NOT REMOVE
-- Original Excel Formula: ={{BaseScale}}*({{ScaleFactor}}^{{Iteration}})
-- This formula is preserved for validation and debugging purposes
-- ============================================================================
CREATE OR REPLACE FUNCTION calc_scales_scale(p_system_id TEXT)
RETURNS NUMERIC AS $$
BEGIN
  RETURN (((COALESCE(calc_scales_base_scale(p_system_id), 0))::numeric * (COALESCE((calc_scales_scale_factor(p_system_id)^(SELECT iteration FROM scales WHERE system_id = p_system_id)), 0))::numeric))::numeric;
END;
$$ LANGUAGE plpgsql;

-- calc_scales_log_scale
-- Field: scales.LogScale
-- Type: calculated | DataType: number | Returns: NUMERIC
-- Formula: =_xlfn.LOG10({{Scale}})
-- ============================================================================
-- CRITICAL FUNCTION VALIDATION CODE - DO NOT REMOVE
-- Original Excel Formula: =_xlfn.LOG10({{Scale}})
-- This formula is preserved for validation and debugging purposes
-- ============================================================================
CREATE OR REPLACE FUNCTION calc_scales_log_scale(p_system_id TEXT)
RETURNS NUMERIC AS $$
BEGIN
  RETURN (_xlfn.LOG10(calc_scales_scale(p_system_id)))::numeric;
END;
$$ LANGUAGE plpgsql;

-- calc_scales_log_measure
-- Field: scales.LogMeasure
-- Type: calculated | DataType: number | Returns: NUMERIC
-- Formula: =_xlfn.LOG10({{Measure}})
-- ============================================================================
-- CRITICAL FUNCTION VALIDATION CODE - DO NOT REMOVE
-- Original Excel Formula: =_xlfn.LOG10({{Measure}})
-- This formula is preserved for validation and debugging purposes
-- ============================================================================
CREATE OR REPLACE FUNCTION calc_scales_log_measure(p_system_id TEXT)
RETURNS NUMERIC AS $$
BEGIN
  RETURN (_xlfn.LOG10((SELECT measure FROM scales WHERE system_id = p_system_id)))::numeric;
END;
$$ LANGUAGE plpgsql;

-- calc_system_stats_point_count
-- Field: system_stats.PointCount
-- Type: aggregation | DataType: integer | Returns: INTEGER
-- Formula: =_xlfn.COUNTIFS(scales!SystemID, {{SystemID}})
-- ============================================================================
-- CRITICAL FUNCTION VALIDATION CODE - DO NOT REMOVE
-- Original Excel Formula: =_xlfn.COUNTIFS(scales!SystemID, {{SystemID}})
-- This formula is preserved for validation and debugging purposes
-- ============================================================================
CREATE OR REPLACE FUNCTION calc_system_stats_point_count(p_system_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN (_xlfn.COUNTIFS(SystemID, (SELECT NULLIF(system_id, '') FROM system_stats WHERE system_id = p_system_id)))::integer;
END;
$$ LANGUAGE plpgsql;

-- calc_system_stats_min_log_scale
-- Field: system_stats.MinLogScale
-- Type: aggregation | DataType: number | Returns: NUMERIC
-- Formula: =_xlfn.MINIFS(scales!LogScale, scales!SystemID, {{SystemID}})
-- ============================================================================
-- CRITICAL FUNCTION VALIDATION CODE - DO NOT REMOVE
-- Original Excel Formula: =_xlfn.MINIFS(scales!LogScale, scales!SystemID, {{SystemID}})
-- This formula is preserved for validation and debugging purposes
-- ============================================================================
CREATE OR REPLACE FUNCTION calc_system_stats_min_log_scale(p_system_id TEXT)
RETURNS NUMERIC AS $$
BEGIN
  RETURN (_xlfn.MINIFS(LogScale, SystemID, (SELECT NULLIF(system_id, '') FROM system_stats WHERE system_id = p_system_id)))::numeric;
END;
$$ LANGUAGE plpgsql;

-- calc_system_stats_max_log_scale
-- Field: system_stats.MaxLogScale
-- Type: aggregation | DataType: number | Returns: NUMERIC
-- Formula: =_xlfn.MAXIFS(scales!LogScale, scales!SystemID, {{SystemID}})
-- ============================================================================
-- CRITICAL FUNCTION VALIDATION CODE - DO NOT REMOVE
-- Original Excel Formula: =_xlfn.MAXIFS(scales!LogScale, scales!SystemID, {{SystemID}})
-- This formula is preserved for validation and debugging purposes
-- ============================================================================
CREATE OR REPLACE FUNCTION calc_system_stats_max_log_scale(p_system_id TEXT)
RETURNS NUMERIC AS $$
BEGIN
  RETURN (_xlfn.MAXIFS(LogScale, SystemID, (SELECT NULLIF(system_id, '') FROM system_stats WHERE system_id = p_system_id)))::numeric;
END;
$$ LANGUAGE plpgsql;

-- calc_system_stats_min_log_measure
-- Field: system_stats.MinLogMeasure
-- Type: aggregation | DataType: number | Returns: NUMERIC
-- Formula: =_xlfn.MINIFS(scales!LogMeasure, scales!SystemID, {{SystemID}})
-- ============================================================================
-- CRITICAL FUNCTION VALIDATION CODE - DO NOT REMOVE
-- Original Excel Formula: =_xlfn.MINIFS(scales!LogMeasure, scales!SystemID, {{SystemID}})
-- This formula is preserved for validation and debugging purposes
-- ============================================================================
CREATE OR REPLACE FUNCTION calc_system_stats_min_log_measure(p_system_id TEXT)
RETURNS NUMERIC AS $$
BEGIN
  RETURN (_xlfn.MINIFS(LogMeasure, SystemID, (SELECT NULLIF(system_id, '') FROM system_stats WHERE system_id = p_system_id)))::numeric;
END;
$$ LANGUAGE plpgsql;

-- calc_system_stats_max_log_measure
-- Field: system_stats.MaxLogMeasure
-- Type: aggregation | DataType: number | Returns: NUMERIC
-- Formula: =_xlfn.MAXIFS(scales!LogMeasure, scales!SystemID, {{SystemID}})
-- ============================================================================
-- CRITICAL FUNCTION VALIDATION CODE - DO NOT REMOVE
-- Original Excel Formula: =_xlfn.MAXIFS(scales!LogMeasure, scales!SystemID, {{SystemID}})
-- This formula is preserved for validation and debugging purposes
-- ============================================================================
CREATE OR REPLACE FUNCTION calc_system_stats_max_log_measure(p_system_id TEXT)
RETURNS NUMERIC AS $$
BEGIN
  RETURN (_xlfn.MAXIFS(LogMeasure, SystemID, (SELECT NULLIF(system_id, '') FROM system_stats WHERE system_id = p_system_id)))::numeric;
END;
$$ LANGUAGE plpgsql;

-- calc_system_stats_empirical_log_log_slope
-- Field: system_stats.EmpiricalLogLogSlope
-- Type: calculated | DataType: number | Returns: NUMERIC
-- Formula: =( {{MinLogMeasure}} - {{MaxLogMeasure}} ) / ( {{MaxLogScale}} - {{MinLogScale}} )
-- ============================================================================
-- CRITICAL FUNCTION VALIDATION CODE - DO NOT REMOVE
-- Original Excel Formula: =( {{MinLogMeasure}} - {{MaxLogMeasure}} ) / ( {{MaxLogScale}} - {{MinLogScale}} )
-- This formula is preserved for validation and debugging purposes
-- ============================================================================
CREATE OR REPLACE FUNCTION calc_system_stats_empirical_log_log_slope(p_system_id TEXT)
RETURNS NUMERIC AS $$
BEGIN
  RETURN (((COALESCE(( calc_system_stats_min_log_measure(p_system_id) - calc_system_stats_max_log_measure(p_system_id) ), 0))::numeric / (COALESCE(( calc_system_stats_max_log_scale(p_system_id) - calc_system_stats_min_log_scale(p_system_id) ), 0))::numeric))::numeric;
END;
$$ LANGUAGE plpgsql;

