-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Views: 7
-- ============================================================================

-- systems View
-- Includes all base table columns (raw + FK) for updatable view support
CREATE OR REPLACE VIEW vw_systems AS
SELECT
  t.system_id,
  t.display_name,
  t.class,
  t.base_scale,
  t.scale_factor,
  t.measure_name,
  t.fractal_dimension,
  t.theoretical_log_log_slope
FROM systems t;

-- scales View
-- Includes all base table columns (raw + FK) for updatable view support
CREATE OR REPLACE VIEW vw_scales AS
SELECT
  t.scale_id,
  t."system",
  t.iteration,
  t.measure,
  t.is_projected,
  t.data_regime,
  t.measurement_model,
  calc_scales_base_scale(t.scale_id) AS base_scale,
  calc_scales_scale_factor(t.scale_id) AS scale_factor,
  calc_scales_scale_factor_power(t.scale_id) AS scale_factor_power,
  calc_scales_scale(t.scale_id) AS scale,
  calc_scales_log_scale(t.scale_id) AS log_scale,
  calc_scales_log_measure(t.scale_id) AS log_measure
FROM scales t;

-- system_stats View
-- Includes all base table columns (raw + FK) for updatable view support
CREATE OR REPLACE VIEW vw_system_stats AS
SELECT
  t.system_stats_id,
  t."system",
  t.analysis_name,
  t.status,
  calc_system_stats_system_display_name(t.system_stats_id) AS system_display_name,
  calc_system_stats_theoretical_log_log_slope(t.system_stats_id) AS theoretical_log_log_slope,
  calc_system_stats_point_count(t.system_stats_id) AS point_count,
  calc_system_stats_min_log_scale(t.system_stats_id) AS min_log_scale,
  calc_system_stats_max_log_scale(t.system_stats_id) AS max_log_scale,
  calc_system_stats_min_log_measure(t.system_stats_id) AS min_log_measure,
  calc_system_stats_max_log_measure(t.system_stats_id) AS max_log_measure,
  calc_system_stats_delta_log_measure(t.system_stats_id) AS delta_log_measure,
  calc_system_stats_delta_log_scale(t.system_stats_id) AS delta_log_scale,
  calc_system_stats_empirical_log_log_slope(t.system_stats_id) AS empirical_log_log_slope,
  calc_system_stats_slope_error(t.system_stats_id) AS slope_error
FROM system_stats t;

-- measurement_models View
-- Includes all base table columns (raw + FK) for updatable view support
CREATE OR REPLACE VIEW vw_measurement_models AS
SELECT
  t.measurement_model_id,
  t."system",
  t.data_regime,
  t.scale_regime,
  t.noise_type,
  t.noise_sigma,
  t.cutoff_min_scale,
  t.cutoff_max_scale,
  t.discretization_type,
  t.discretization_param
FROM measurement_models t;

-- observed_scales View
-- Includes all base table columns (raw + FK) for updatable view support
CREATE OR REPLACE VIEW vw_observed_scales AS
SELECT
  t.observed_scale_id,
  t."system",
  t.measurement_model,
  t.iteration,
  t.measure,
  t.data_regime,
  calc_observed_scales_base_scale(t.observed_scale_id) AS base_scale,
  calc_observed_scales_scale_factor(t.observed_scale_id) AS scale_factor,
  calc_observed_scales_scale_factor_power(t.observed_scale_id) AS scale_factor_power,
  calc_observed_scales_scale(t.observed_scale_id) AS scale,
  calc_observed_scales_log_scale(t.observed_scale_id) AS log_scale,
  calc_observed_scales_log_measure(t.observed_scale_id) AS log_measure
FROM observed_scales t;

-- inference_runs View
-- Includes all base table columns (raw + FK) for updatable view support
CREATE OR REPLACE VIEW vw_inference_runs AS
SELECT
  t.inference_run_id,
  t."system",
  t.data_regime,
  t.measurement_model,
  t.fit_method,
  t.fitted_slope,
  t.fitted_intercept,
  t.r2,
  t.residual_rms,
  t.residual_max_abs,
  t.orthogonal_rms,
  calc_inference_runs_theoretical_log_log_slope(t.inference_run_id) AS theoretical_log_log_slope,
  calc_inference_runs_point_count(t.inference_run_id) AS point_count,
  calc_inference_runs_slope_delta(t.inference_run_id) AS slope_delta,
  calc_inference_runs_deviation_score(t.inference_run_id) AS deviation_score
FROM inference_runs t;

-- scale_regimes View
-- Includes all base table columns (raw + FK) for updatable view support
CREATE OR REPLACE VIEW vw_scale_regimes AS
SELECT

FROM scale_regimes t;

